// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function RecConnect(arg1:string):Promise<string>;

export function RecGetMetadata():Promise<Array<string>>;

export function SendConnect(arg1:string):Promise<void>;

export function SendGetFiles(arg1:Array<string>):Promise<Array<string>>;

export function SendGetIncrementalStats():Promise<Array<main.IncStats>>;

export function SendGetSDP(arg1:number,arg2:Array<string>):Promise<string>;

export function SendGetStats():Promise<main.Stats>;

export function SendOpenFilePicker():Promise<Array<string>>;
