// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RecConnect(arg1) {
  return window['go']['main']['App']['RecConnect'](arg1);
}

export function RecConsentNo() {
  return window['go']['main']['App']['RecConsentNo']();
}

export function RecConsentYes() {
  return window['go']['main']['App']['RecConsentYes']();
}

export function RecGetIncrementalStats() {
  return window['go']['main']['App']['RecGetIncrementalStats']();
}

export function RecGetMetadata() {
  return window['go']['main']['App']['RecGetMetadata']();
}

export function RecGetStats() {
  return window['go']['main']['App']['RecGetStats']();
}

export function SendConnect(arg1) {
  return window['go']['main']['App']['SendConnect'](arg1);
}

export function SendGetFiles(arg1) {
  return window['go']['main']['App']['SendGetFiles'](arg1);
}

export function SendGetIncrementalStats() {
  return window['go']['main']['App']['SendGetIncrementalStats']();
}

export function SendGetSDP(arg1, arg2) {
  return window['go']['main']['App']['SendGetSDP'](arg1, arg2);
}

export function SendGetStats() {
  return window['go']['main']['App']['SendGetStats']();
}

export function SendOpenFilePicker() {
  return window['go']['main']['App']['SendOpenFilePicker']();
}
