// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:string):Promise<void>;

export function GetSDP(arg1:number,arg2:Array<string>):Promise<string>;

export function GetStats():Promise<main.Stats>;

export function OpenFilePicker():Promise<Array<string>>;
