// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function GetFiles(arg1) {
  return window['go']['main']['App']['GetFiles'](arg1);
}

export function GetIncrementalStats() {
  return window['go']['main']['App']['GetIncrementalStats']();
}

export function GetSDP(arg1, arg2) {
  return window['go']['main']['App']['GetSDP'](arg1, arg2);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function OpenFilePicker() {
  return window['go']['main']['App']['OpenFilePicker']();
}
